{{- if eq .Values.mode "hosted" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.hosted.serviceAccountName }}-token
  namespace: {{ .Values.hosted.namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.hosted.serviceAccountName }}
type: kubernetes.io/service-account-token
{{- end }}
