{{- if eq .Values.mode "management" }}
apiVersion: v1
kind: Secret
metadata:
  name: hcp-scheduler-metrics-token
  namespace: {{ required "A valid management.hcpNamespace is required when mode=management!" .Values.management.hcpNamespace }}
type: Opaque
stringData:
  token: {{ required "A valid management.bearerToken is required when mode=management!" .Values.management.bearerToken }}
{{- end }}
